### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by mikicho** [DoclerLabs/hexMachina-Gallery-Classical-MVC#3]
Hey,  
I tried to build the project and I get:
```
src/example/Main.hx:16: characters 18-47 : Type not found : hex.log.layout.LogProxyLayout
src/example/Main.hx:17: characters 23-55 : Type not found : hex.log.layout.LogLayoutHTMLView
src/example/Main.hx:18: characters 25-59 : Type not found : hex.log.layout.SimpleBrowserLayout
src/example/Main.hx:26: characters 2-25 : Class<hex.compiler.parser.xml.XmlCompiler> has no field readXmlFile
```

**Comment by aliokan** [comment]
Hello, 

Logging system has his own repository [hexLog](https://github.com/DoclerLabs/hexLog) since hexMachina 0.16.0, and logging API has completely changed. 
I have just made all changes needed be able to compile in hexMachina 0.22.0.  DoclerLabs/hexMachina-Gallery-Classical-MVC@d71ab59ec48b85d06e967e0c0d4caaa0783f697d
